In [4]:
import pandas as pd

In [3]:
df = pd.read_csv("/content/netflix_movies_tv_shows.csv")

## 1.How big is the Data ?

In [5]:
df

,title,type,genre,release_year,imdb_rating,vote_count,budget_million_usd,collection_million_usd,popularity_score,awards_won
0,Hidden Frontier 7484,Movie,Documentary,2021,7.33,99818,56.31,208.58,43.28,5
1,Rising Hunter 4997,TV Show,Sci-Fi,2016,7.66,153360,75.23,317.24,14.71,7
2,Iron Code 6096,Movie,Sci-Fi,2008,6.80,778915,22.09,21.05,79.08,3
3,Emerald Chronicle 6992,Movie,Horror,2000,5.25,620369,187.71,296.48,47.49,17
4,Lonely River 5722,Movie,Documentary,2020,6.51,562165,112.99,128.68,84.00,10
...,...,...,...,...,...,...,...,...,...,...
495,Neon Storm 3858,Movie,Sci-Fi,2021,5.36,20169,74.77,205.75,69.98,7
496,Rising City 1771,Movie,Drama,2022,9.03,519652,101.37,248.08,80.86,19
497,Rising Network 6931,TV Show,Thriller,2024,7.46,119413,166.51,426.21,50.89,17
498,Crimson Truth 8359,Movie,Horror,2000,8.68,644552,70.37,101.33,66.72,12
499,Rising Odyssey 2193,TV Show,Action,2021,7.04,268926,38.88,83.95,32.35,15

## 2. How does the Data look like ?

In [6]:
df.sample(10)

,title,type,genre,release_year,imdb_rating,vote_count,budget_million_usd,collection_million_usd,popularity_score,awards_won
212,Iron Mission 7232,Movie,Drama,2018,8.80,795557,197.01,610.22,49.30,4
168,Silent Labyrinth 1964,Movie,Sci-Fi,2001,5.34,534398,45.11,206.80,93.36,1
61,Fallen Storm 1153,Movie,Action,2013,8.22,280922,94.66,457.46,43.46,8
146,Ancient Network 1251,Movie,Sci-Fi,2003,7.71,218285,18.90,18.64,98.31,0
372,Golden Memory 6820,TV Show,Comedy,2009,5.31,462792,86.66,357.04,15.09,19
48,Wild Odyssey 1651,TV Show,Comedy,2004,6.98,379544,193.34,946.52,56.92,9
166,Emerald Journey 5806,TV Show,Romance,2011,8.47,7570,126.81,304.12,10.81,18
327,Iron Network 7209,Movie,Comedy,2012,8.05,746385,169.18,689.23,97.32,10
399,Crimson Frontier 2768,Movie,Action,2005,8.12,258681,99.52,99.47,53.47,16
276,Silent Truth 2858,Movie,Drama,2023,7.92,54551,130.25,249.15,77.88,4

## 3.What is the Datatype the columns ?

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 10 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   title                   500 non-null    object
 1   type                    500 non-null    object
 2   genre                   500 non-null    object
 3   release_year            500 non-null    int64
 4   imdb_rating             500 non-null    float64
 5   vote_count              500 non-null    int64
 6   budget_million_usd      500 non-null    float64
 7   collection_million_usd  500 non-null    float64
 8   popularity_score        500 non-null    float64
 9   awards_won              500 non-null    int64
dtypes: float64(4), int64(3), object(3)
memory usage: 39.2+ KB

## 4. Are there any missing values ?

In [8]:
df.isnull().sum()

title                     0
type                      0
genre                     0
release_year              0
imdb_rating               0
vote_count                0
budget_million_usd        0
collection_million_usd    0
popularity_score          0
awards_won                0
dtype: int64

## 5.How does the data look mathematicaly

In [9]:
df.describe()

,release_year,imdb_rating,vote_count,budget_million_usd,collection_million_usd,popularity_score,awards_won
count,500.000000,500.000000,500.000000,500.000000,500.000000,500.000000,500.000000
mean,2011.574000,7.222040,398879.564000,102.926440,279.364560,55.162080,9.904000
std,7.404741,1.329844,233830.166222,56.497841,210.611678,26.274685,5.617642
min,2000.000000,5.020000,7570.000000,5.630000,3.410000,10.000000,0.000000
25%,2005.000000,6.037500,197540.000000,53.535000,101.712500,33.155000,5.000000
50%,2012.000000,7.230000,385665.000000,103.670000,229.840000,55.485000,10.000000
75%,2018.000000,8.395000,614375.000000,153.397500,398.837500,77.407500,15.000000
max,2024.000000,9.490000,797657.000000,199.680000,946.520000,99.530000,19.000000

##6. Are there Duplicate values ?

In [11]:
df.duplicated().sum()

np.int64(0)

##7.How is the correlation between columns

In [10]:
df.corr(numeric_only=True)

,release_year,imdb_rating,vote_count,budget_million_usd,collection_million_usd,popularity_score,awards_won
release_year,1.000000,0.030351,-0.019653,0.031874,0.029791,-0.020154,-0.017365
imdb_rating,0.030351,1.000000,-0.024786,0.010878,-0.011826,-0.032137,0.094830
vote_count,-0.019653,-0.024786,1.000000,0.009559,0.045776,0.059608,0.031006
budget_million_usd,0.031874,0.010878,0.009559,1.000000,0.712559,-0.043314,0.057527
collection_million_usd,0.029791,-0.011826,0.045776,0.712559,1.000000,-0.046714,0.004230
popularity_score,-0.020154,-0.032137,0.059608,-0.043314,-0.046714,1.000000,-0.017833
awards_won,-0.017365,0.094830,0.031006,0.057527,0.004230,-0.017833,1.000000